on:
  push:
    branches:
      - cv
jobs:
  cv-job:
    runs-on: ubuntu-latest
    name: Create cover letter
    steps:
      - name: Build pdf from tex
        id: build
        uses: Kavinjsir/latex-compiler@v1.4
      - name: View output
        run: ls /github/workspace
