on:
  push:
    branches:
      - cv
jobs:
  cv-job:
    runs-on: ubuntu-latest
    name: Create cover letter
    steps:
      - uses: actions/checkout@v3
        with:
          ref: cv
      - name: Move to cv directory
        id: move
        run: cd ${GITHUB_WORKSPACE}/cv
      - name: Build Latex image
        id: build
        run: docker build -t latex-compiler .
      - name: Create cover letter
        id: compile
        run: docker run --rm -v ${GITHUB_WORKSPACE}/cv:/data tx xelatex resume.tex
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: ${GITHUB_WORKSPACE}/cv/resume.pdf

